/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SavingRouteImport } from './routes/saving'
import { Route as RetirementRouteImport } from './routes/retirement'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as InvestingRouteImport } from './routes/investing'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as FactCheckingPolicyRouteImport } from './routes/fact-checking-policy'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DebtTaxesInsuranceRouteImport } from './routes/debt-taxes-insurance'
import { Route as CreditCardsRouteImport } from './routes/credit-cards'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BudgetingRouteImport } from './routes/budgeting'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as ToolsSavingsGoalCalculatorRouteImport } from './routes/tools.savings-goal-calculator'
import { Route as ToolsRetirementSavingsCalculatorRouteImport } from './routes/tools.retirement-savings-calculator'
import { Route as ToolsEmergencyFundCalculatorRouteImport } from './routes/tools.emergency-fund-calculator'
import { Route as ToolsDebtPayoffCalculatorRouteImport } from './routes/tools.debt-payoff-calculator'
import { Route as ToolsCreditScoreEstimatorRouteImport } from './routes/tools.credit-score-estimator'
import { Route as ToolsCreditCardPayoffCalculatorRouteImport } from './routes/tools.credit-card-payoff-calculator'
import { Route as ToolsCompoundInterestCalculatorRouteImport } from './routes/tools.compound-interest-calculator'
import { Route as ToolsBudgetPlannerRouteImport } from './routes/tools.budget-planner'
import { Route as AboutYinkaOlayokunRouteImport } from './routes/about.yinka-olayokun'
import { Route as PillarPostRouteImport } from './routes/$pillar.$post'
import { Route as ApiPublicNewsletterRouteImport } from './routes/api/public/newsletter'
import { Route as PillarVsMatchupRouteImport } from './routes/$pillar.vs.$matchup'
import { Route as PillarRulesSlugRouteImport } from './routes/$pillar.rules.$slug'
import { Route as PillarDecideSlugRouteImport } from './routes/$pillar.decide.$slug'
import { Route as PillarBestSlugRouteImport } from './routes/$pillar.best.$slug'
import { Route as PillarBestForPersonaRouteImport } from './routes/$pillar.best-for.$persona'
import { Route as PillarAnswersSlugRouteImport } from './routes/$pillar.answers.$slug'
import { Route as ApiPublicNewsletterCronRouteImport } from './routes/api/public/newsletter.cron'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingRoute = SavingRouteImport.update({
  id: '/saving',
  path: '/saving',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirementRoute = RetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingRoute = InvestingRouteImport.update({
  id: '/investing',
  path: '/investing',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckingPolicyRoute = FactCheckingPolicyRouteImport.update({
  id: '/fact-checking-policy',
  path: '/fact-checking-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtTaxesInsuranceRoute = DebtTaxesInsuranceRouteImport.update({
  id: '/debt-taxes-insurance',
  path: '/debt-taxes-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardsRoute = CreditCardsRouteImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetingRoute = BudgetingRouteImport.update({
  id: '/budgeting',
  path: '/budgeting',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSavingsGoalCalculatorRoute =
  ToolsSavingsGoalCalculatorRouteImport.update({
    id: '/tools/savings-goal-calculator',
    path: '/tools/savings-goal-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsRetirementSavingsCalculatorRoute =
  ToolsRetirementSavingsCalculatorRouteImport.update({
    id: '/tools/retirement-savings-calculator',
    path: '/tools/retirement-savings-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsEmergencyFundCalculatorRoute =
  ToolsEmergencyFundCalculatorRouteImport.update({
    id: '/tools/emergency-fund-calculator',
    path: '/tools/emergency-fund-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsDebtPayoffCalculatorRoute =
  ToolsDebtPayoffCalculatorRouteImport.update({
    id: '/tools/debt-payoff-calculator',
    path: '/tools/debt-payoff-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCreditScoreEstimatorRoute =
  ToolsCreditScoreEstimatorRouteImport.update({
    id: '/tools/credit-score-estimator',
    path: '/tools/credit-score-estimator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCreditCardPayoffCalculatorRoute =
  ToolsCreditCardPayoffCalculatorRouteImport.update({
    id: '/tools/credit-card-payoff-calculator',
    path: '/tools/credit-card-payoff-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCompoundInterestCalculatorRoute =
  ToolsCompoundInterestCalculatorRouteImport.update({
    id: '/tools/compound-interest-calculator',
    path: '/tools/compound-interest-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsBudgetPlannerRoute = ToolsBudgetPlannerRouteImport.update({
  id: '/tools/budget-planner',
  path: '/tools/budget-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutYinkaOlayokunRoute = AboutYinkaOlayokunRouteImport.update({
  id: '/about/yinka-olayokun',
  path: '/about/yinka-olayokun',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarPostRoute = PillarPostRouteImport.update({
  id: '/$pillar/$post',
  path: '/$pillar/$post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterRoute = ApiPublicNewsletterRouteImport.update({
  id: '/api/public/newsletter',
  path: '/api/public/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarVsMatchupRoute = PillarVsMatchupRouteImport.update({
  id: '/$pillar/vs/$matchup',
  path: '/$pillar/vs/$matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarRulesSlugRoute = PillarRulesSlugRouteImport.update({
  id: '/$pillar/rules/$slug',
  path: '/$pillar/rules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarDecideSlugRoute = PillarDecideSlugRouteImport.update({
  id: '/$pillar/decide/$slug',
  path: '/$pillar/decide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarBestSlugRoute = PillarBestSlugRouteImport.update({
  id: '/$pillar/best/$slug',
  path: '/$pillar/best/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarBestForPersonaRoute = PillarBestForPersonaRouteImport.update({
  id: '/$pillar/best-for/$persona',
  path: '/$pillar/best-for/$persona',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarAnswersSlugRoute = PillarAnswersSlugRouteImport.update({
  id: '/$pillar/answers/$slug',
  path: '/$pillar/answers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterCronRoute = ApiPublicNewsletterCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => ApiPublicNewsletterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banking': typeof BankingRoute
  '/budgeting': typeof BudgetingRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/credit-cards': typeof CreditCardsRoute
  '/debt-taxes-insurance': typeof DebtTaxesInsuranceRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking-policy': typeof FactCheckingPolicyRoute
  '/glossary': typeof GlossaryRoute
  '/investing': typeof InvestingRoute
  '/methodology': typeof MethodologyRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/retirement': typeof RetirementRoute
  '/saving': typeof SavingRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/$pillar/$post': typeof PillarPostRoute
  '/about/yinka-olayokun': typeof AboutYinkaOlayokunRoute
  '/tools/budget-planner': typeof ToolsBudgetPlannerRoute
  '/tools/compound-interest-calculator': typeof ToolsCompoundInterestCalculatorRoute
  '/tools/credit-card-payoff-calculator': typeof ToolsCreditCardPayoffCalculatorRoute
  '/tools/credit-score-estimator': typeof ToolsCreditScoreEstimatorRoute
  '/tools/debt-payoff-calculator': typeof ToolsDebtPayoffCalculatorRoute
  '/tools/emergency-fund-calculator': typeof ToolsEmergencyFundCalculatorRoute
  '/tools/retirement-savings-calculator': typeof ToolsRetirementSavingsCalculatorRoute
  '/tools/savings-goal-calculator': typeof ToolsSavingsGoalCalculatorRoute
  '/about/': typeof AboutIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/$pillar/answers/$slug': typeof PillarAnswersSlugRoute
  '/$pillar/best-for/$persona': typeof PillarBestForPersonaRoute
  '/$pillar/best/$slug': typeof PillarBestSlugRoute
  '/$pillar/decide/$slug': typeof PillarDecideSlugRoute
  '/$pillar/rules/$slug': typeof PillarRulesSlugRoute
  '/$pillar/vs/$matchup': typeof PillarVsMatchupRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRouteWithChildren
  '/api/public/newsletter/cron': typeof ApiPublicNewsletterCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banking': typeof BankingRoute
  '/budgeting': typeof BudgetingRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/credit-cards': typeof CreditCardsRoute
  '/debt-taxes-insurance': typeof DebtTaxesInsuranceRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking-policy': typeof FactCheckingPolicyRoute
  '/glossary': typeof GlossaryRoute
  '/investing': typeof InvestingRoute
  '/methodology': typeof MethodologyRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/retirement': typeof RetirementRoute
  '/saving': typeof SavingRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/$pillar/$post': typeof PillarPostRoute
  '/about/yinka-olayokun': typeof AboutYinkaOlayokunRoute
  '/tools/budget-planner': typeof ToolsBudgetPlannerRoute
  '/tools/compound-interest-calculator': typeof ToolsCompoundInterestCalculatorRoute
  '/tools/credit-card-payoff-calculator': typeof ToolsCreditCardPayoffCalculatorRoute
  '/tools/credit-score-estimator': typeof ToolsCreditScoreEstimatorRoute
  '/tools/debt-payoff-calculator': typeof ToolsDebtPayoffCalculatorRoute
  '/tools/emergency-fund-calculator': typeof ToolsEmergencyFundCalculatorRoute
  '/tools/retirement-savings-calculator': typeof ToolsRetirementSavingsCalculatorRoute
  '/tools/savings-goal-calculator': typeof ToolsSavingsGoalCalculatorRoute
  '/about': typeof AboutIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/$pillar/answers/$slug': typeof PillarAnswersSlugRoute
  '/$pillar/best-for/$persona': typeof PillarBestForPersonaRoute
  '/$pillar/best/$slug': typeof PillarBestSlugRoute
  '/$pillar/decide/$slug': typeof PillarDecideSlugRoute
  '/$pillar/rules/$slug': typeof PillarRulesSlugRoute
  '/$pillar/vs/$matchup': typeof PillarVsMatchupRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRouteWithChildren
  '/api/public/newsletter/cron': typeof ApiPublicNewsletterCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banking': typeof BankingRoute
  '/budgeting': typeof BudgetingRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/credit-cards': typeof CreditCardsRoute
  '/debt-taxes-insurance': typeof DebtTaxesInsuranceRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking-policy': typeof FactCheckingPolicyRoute
  '/glossary': typeof GlossaryRoute
  '/investing': typeof InvestingRoute
  '/methodology': typeof MethodologyRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/retirement': typeof RetirementRoute
  '/saving': typeof SavingRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/$pillar/$post': typeof PillarPostRoute
  '/about/yinka-olayokun': typeof AboutYinkaOlayokunRoute
  '/tools/budget-planner': typeof ToolsBudgetPlannerRoute
  '/tools/compound-interest-calculator': typeof ToolsCompoundInterestCalculatorRoute
  '/tools/credit-card-payoff-calculator': typeof ToolsCreditCardPayoffCalculatorRoute
  '/tools/credit-score-estimator': typeof ToolsCreditScoreEstimatorRoute
  '/tools/debt-payoff-calculator': typeof ToolsDebtPayoffCalculatorRoute
  '/tools/emergency-fund-calculator': typeof ToolsEmergencyFundCalculatorRoute
  '/tools/retirement-savings-calculator': typeof ToolsRetirementSavingsCalculatorRoute
  '/tools/savings-goal-calculator': typeof ToolsSavingsGoalCalculatorRoute
  '/about/': typeof AboutIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/$pillar/answers/$slug': typeof PillarAnswersSlugRoute
  '/$pillar/best-for/$persona': typeof PillarBestForPersonaRoute
  '/$pillar/best/$slug': typeof PillarBestSlugRoute
  '/$pillar/decide/$slug': typeof PillarDecideSlugRoute
  '/$pillar/rules/$slug': typeof PillarRulesSlugRoute
  '/$pillar/vs/$matchup': typeof PillarVsMatchupRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRouteWithChildren
  '/api/public/newsletter/cron': typeof ApiPublicNewsletterCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banking'
    | '/budgeting'
    | '/contact'
    | '/corrections'
    | '/credit-cards'
    | '/debt-taxes-insurance'
    | '/disclaimer'
    | '/editorial-policy'
    | '/fact-checking-policy'
    | '/glossary'
    | '/investing'
    | '/methodology'
    | '/newsletter'
    | '/privacy'
    | '/retirement'
    | '/saving'
    | '/terms'
    | '/topics'
    | '/$pillar/$post'
    | '/about/yinka-olayokun'
    | '/tools/budget-planner'
    | '/tools/compound-interest-calculator'
    | '/tools/credit-card-payoff-calculator'
    | '/tools/credit-score-estimator'
    | '/tools/debt-payoff-calculator'
    | '/tools/emergency-fund-calculator'
    | '/tools/retirement-savings-calculator'
    | '/tools/savings-goal-calculator'
    | '/about/'
    | '/tools/'
    | '/$pillar/answers/$slug'
    | '/$pillar/best-for/$persona'
    | '/$pillar/best/$slug'
    | '/$pillar/decide/$slug'
    | '/$pillar/rules/$slug'
    | '/$pillar/vs/$matchup'
    | '/api/public/newsletter'
    | '/api/public/newsletter/cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banking'
    | '/budgeting'
    | '/contact'
    | '/corrections'
    | '/credit-cards'
    | '/debt-taxes-insurance'
    | '/disclaimer'
    | '/editorial-policy'
    | '/fact-checking-policy'
    | '/glossary'
    | '/investing'
    | '/methodology'
    | '/newsletter'
    | '/privacy'
    | '/retirement'
    | '/saving'
    | '/terms'
    | '/topics'
    | '/$pillar/$post'
    | '/about/yinka-olayokun'
    | '/tools/budget-planner'
    | '/tools/compound-interest-calculator'
    | '/tools/credit-card-payoff-calculator'
    | '/tools/credit-score-estimator'
    | '/tools/debt-payoff-calculator'
    | '/tools/emergency-fund-calculator'
    | '/tools/retirement-savings-calculator'
    | '/tools/savings-goal-calculator'
    | '/about'
    | '/tools'
    | '/$pillar/answers/$slug'
    | '/$pillar/best-for/$persona'
    | '/$pillar/best/$slug'
    | '/$pillar/decide/$slug'
    | '/$pillar/rules/$slug'
    | '/$pillar/vs/$matchup'
    | '/api/public/newsletter'
    | '/api/public/newsletter/cron'
  id:
    | '__root__'
    | '/'
    | '/banking'
    | '/budgeting'
    | '/contact'
    | '/corrections'
    | '/credit-cards'
    | '/debt-taxes-insurance'
    | '/disclaimer'
    | '/editorial-policy'
    | '/fact-checking-policy'
    | '/glossary'
    | '/investing'
    | '/methodology'
    | '/newsletter'
    | '/privacy'
    | '/retirement'
    | '/saving'
    | '/terms'
    | '/topics'
    | '/$pillar/$post'
    | '/about/yinka-olayokun'
    | '/tools/budget-planner'
    | '/tools/compound-interest-calculator'
    | '/tools/credit-card-payoff-calculator'
    | '/tools/credit-score-estimator'
    | '/tools/debt-payoff-calculator'
    | '/tools/emergency-fund-calculator'
    | '/tools/retirement-savings-calculator'
    | '/tools/savings-goal-calculator'
    | '/about/'
    | '/tools/'
    | '/$pillar/answers/$slug'
    | '/$pillar/best-for/$persona'
    | '/$pillar/best/$slug'
    | '/$pillar/decide/$slug'
    | '/$pillar/rules/$slug'
    | '/$pillar/vs/$matchup'
    | '/api/public/newsletter'
    | '/api/public/newsletter/cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankingRoute: typeof BankingRoute
  BudgetingRoute: typeof BudgetingRoute
  ContactRoute: typeof ContactRoute
  CorrectionsRoute: typeof CorrectionsRoute
  CreditCardsRoute: typeof CreditCardsRoute
  DebtTaxesInsuranceRoute: typeof DebtTaxesInsuranceRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FactCheckingPolicyRoute: typeof FactCheckingPolicyRoute
  GlossaryRoute: typeof GlossaryRoute
  InvestingRoute: typeof InvestingRoute
  MethodologyRoute: typeof MethodologyRoute
  NewsletterRoute: typeof NewsletterRoute
  PrivacyRoute: typeof PrivacyRoute
  RetirementRoute: typeof RetirementRoute
  SavingRoute: typeof SavingRoute
  TermsRoute: typeof TermsRoute
  TopicsRoute: typeof TopicsRoute
  PillarPostRoute: typeof PillarPostRoute
  AboutYinkaOlayokunRoute: typeof AboutYinkaOlayokunRoute
  ToolsBudgetPlannerRoute: typeof ToolsBudgetPlannerRoute
  ToolsCompoundInterestCalculatorRoute: typeof ToolsCompoundInterestCalculatorRoute
  ToolsCreditCardPayoffCalculatorRoute: typeof ToolsCreditCardPayoffCalculatorRoute
  ToolsCreditScoreEstimatorRoute: typeof ToolsCreditScoreEstimatorRoute
  ToolsDebtPayoffCalculatorRoute: typeof ToolsDebtPayoffCalculatorRoute
  ToolsEmergencyFundCalculatorRoute: typeof ToolsEmergencyFundCalculatorRoute
  ToolsRetirementSavingsCalculatorRoute: typeof ToolsRetirementSavingsCalculatorRoute
  ToolsSavingsGoalCalculatorRoute: typeof ToolsSavingsGoalCalculatorRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  PillarAnswersSlugRoute: typeof PillarAnswersSlugRoute
  PillarBestForPersonaRoute: typeof PillarBestForPersonaRoute
  PillarBestSlugRoute: typeof PillarBestSlugRoute
  PillarDecideSlugRoute: typeof PillarDecideSlugRoute
  PillarRulesSlugRoute: typeof PillarRulesSlugRoute
  PillarVsMatchupRoute: typeof PillarVsMatchupRoute
  ApiPublicNewsletterRoute: typeof ApiPublicNewsletterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saving': {
      id: '/saving'
      path: '/saving'
      fullPath: '/saving'
      preLoaderRoute: typeof SavingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirement': {
      id: '/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof RetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing': {
      id: '/investing'
      path: '/investing'
      fullPath: '/investing'
      preLoaderRoute: typeof InvestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-checking-policy': {
      id: '/fact-checking-policy'
      path: '/fact-checking-policy'
      fullPath: '/fact-checking-policy'
      preLoaderRoute: typeof FactCheckingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debt-taxes-insurance': {
      id: '/debt-taxes-insurance'
      path: '/debt-taxes-insurance'
      fullPath: '/debt-taxes-insurance'
      preLoaderRoute: typeof DebtTaxesInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-cards': {
      id: '/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof CreditCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgeting': {
      id: '/budgeting'
      path: '/budgeting'
      fullPath: '/budgeting'
      preLoaderRoute: typeof BudgetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/savings-goal-calculator': {
      id: '/tools/savings-goal-calculator'
      path: '/tools/savings-goal-calculator'
      fullPath: '/tools/savings-goal-calculator'
      preLoaderRoute: typeof ToolsSavingsGoalCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/retirement-savings-calculator': {
      id: '/tools/retirement-savings-calculator'
      path: '/tools/retirement-savings-calculator'
      fullPath: '/tools/retirement-savings-calculator'
      preLoaderRoute: typeof ToolsRetirementSavingsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/emergency-fund-calculator': {
      id: '/tools/emergency-fund-calculator'
      path: '/tools/emergency-fund-calculator'
      fullPath: '/tools/emergency-fund-calculator'
      preLoaderRoute: typeof ToolsEmergencyFundCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/debt-payoff-calculator': {
      id: '/tools/debt-payoff-calculator'
      path: '/tools/debt-payoff-calculator'
      fullPath: '/tools/debt-payoff-calculator'
      preLoaderRoute: typeof ToolsDebtPayoffCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/credit-score-estimator': {
      id: '/tools/credit-score-estimator'
      path: '/tools/credit-score-estimator'
      fullPath: '/tools/credit-score-estimator'
      preLoaderRoute: typeof ToolsCreditScoreEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/credit-card-payoff-calculator': {
      id: '/tools/credit-card-payoff-calculator'
      path: '/tools/credit-card-payoff-calculator'
      fullPath: '/tools/credit-card-payoff-calculator'
      preLoaderRoute: typeof ToolsCreditCardPayoffCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compound-interest-calculator': {
      id: '/tools/compound-interest-calculator'
      path: '/tools/compound-interest-calculator'
      fullPath: '/tools/compound-interest-calculator'
      preLoaderRoute: typeof ToolsCompoundInterestCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/budget-planner': {
      id: '/tools/budget-planner'
      path: '/tools/budget-planner'
      fullPath: '/tools/budget-planner'
      preLoaderRoute: typeof ToolsBudgetPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/yinka-olayokun': {
      id: '/about/yinka-olayokun'
      path: '/about/yinka-olayokun'
      fullPath: '/about/yinka-olayokun'
      preLoaderRoute: typeof AboutYinkaOlayokunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pillar/$post': {
      id: '/$pillar/$post'
      path: '/$pillar/$post'
      fullPath: '/$pillar/$post'
      preLoaderRoute: typeof PillarPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter': {
      id: '/api/public/newsletter'
      path: '/api/public/newsletter'
      fullPath: '/api/public/newsletter'
      preLoaderRoute: typeof ApiPublicNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pillar/vs/$matchup': {
      id: '/$pillar/vs/$matchup'
      path: '/$pillar/vs/$matchup'
      fullPath: '/$pillar/vs/$matchup'
      preLoaderRoute: typeof PillarVsMatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pillar/rules/$slug': {
      id: '/$pillar/rules/$slug'
      path: '/$pillar/rules/$slug'
      fullPath: '/$pillar/rules/$slug'
      preLoaderRoute: typeof PillarRulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pillar/decide/$slug': {
      id: '/$pillar/decide/$slug'
      path: '/$pillar/decide/$slug'
      fullPath: '/$pillar/decide/$slug'
      preLoaderRoute: typeof PillarDecideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pillar/best/$slug': {
      id: '/$pillar/best/$slug'
      path: '/$pillar/best/$slug'
      fullPath: '/$pillar/best/$slug'
      preLoaderRoute: typeof PillarBestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pillar/best-for/$persona': {
      id: '/$pillar/best-for/$persona'
      path: '/$pillar/best-for/$persona'
      fullPath: '/$pillar/best-for/$persona'
      preLoaderRoute: typeof PillarBestForPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pillar/answers/$slug': {
      id: '/$pillar/answers/$slug'
      path: '/$pillar/answers/$slug'
      fullPath: '/$pillar/answers/$slug'
      preLoaderRoute: typeof PillarAnswersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter/cron': {
      id: '/api/public/newsletter/cron'
      path: '/cron'
      fullPath: '/api/public/newsletter/cron'
      preLoaderRoute: typeof ApiPublicNewsletterCronRouteImport
      parentRoute: typeof ApiPublicNewsletterRoute
    }
  }
}

interface ApiPublicNewsletterRouteChildren {
  ApiPublicNewsletterCronRoute: typeof ApiPublicNewsletterCronRoute
}

const ApiPublicNewsletterRouteChildren: ApiPublicNewsletterRouteChildren = {
  ApiPublicNewsletterCronRoute: ApiPublicNewsletterCronRoute,
}

const ApiPublicNewsletterRouteWithChildren =
  ApiPublicNewsletterRoute._addFileChildren(ApiPublicNewsletterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankingRoute: BankingRoute,
  BudgetingRoute: BudgetingRoute,
  ContactRoute: ContactRoute,
  CorrectionsRoute: CorrectionsRoute,
  CreditCardsRoute: CreditCardsRoute,
  DebtTaxesInsuranceRoute: DebtTaxesInsuranceRoute,
  DisclaimerRoute: DisclaimerRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FactCheckingPolicyRoute: FactCheckingPolicyRoute,
  GlossaryRoute: GlossaryRoute,
  InvestingRoute: InvestingRoute,
  MethodologyRoute: MethodologyRoute,
  NewsletterRoute: NewsletterRoute,
  PrivacyRoute: PrivacyRoute,
  RetirementRoute: RetirementRoute,
  SavingRoute: SavingRoute,
  TermsRoute: TermsRoute,
  TopicsRoute: TopicsRoute,
  PillarPostRoute: PillarPostRoute,
  AboutYinkaOlayokunRoute: AboutYinkaOlayokunRoute,
  ToolsBudgetPlannerRoute: ToolsBudgetPlannerRoute,
  ToolsCompoundInterestCalculatorRoute: ToolsCompoundInterestCalculatorRoute,
  ToolsCreditCardPayoffCalculatorRoute: ToolsCreditCardPayoffCalculatorRoute,
  ToolsCreditScoreEstimatorRoute: ToolsCreditScoreEstimatorRoute,
  ToolsDebtPayoffCalculatorRoute: ToolsDebtPayoffCalculatorRoute,
  ToolsEmergencyFundCalculatorRoute: ToolsEmergencyFundCalculatorRoute,
  ToolsRetirementSavingsCalculatorRoute: ToolsRetirementSavingsCalculatorRoute,
  ToolsSavingsGoalCalculatorRoute: ToolsSavingsGoalCalculatorRoute,
  AboutIndexRoute: AboutIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  PillarAnswersSlugRoute: PillarAnswersSlugRoute,
  PillarBestForPersonaRoute: PillarBestForPersonaRoute,
  PillarBestSlugRoute: PillarBestSlugRoute,
  PillarDecideSlugRoute: PillarDecideSlugRoute,
  PillarRulesSlugRoute: PillarRulesSlugRoute,
  PillarVsMatchupRoute: PillarVsMatchupRoute,
  ApiPublicNewsletterRoute: ApiPublicNewsletterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
