/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SavingRouteImport } from './routes/saving'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RetirementRouteImport } from './routes/retirement'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as InvestingRouteImport } from './routes/investing'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DebtTaxesInsuranceRouteImport } from './routes/debt-taxes-insurance'
import { Route as CreditCardsRouteImport } from './routes/credit-cards'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BudgetingRouteImport } from './routes/budgeting'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as ToolsSavingsGoalCalculatorRouteImport } from './routes/tools.savings-goal-calculator'
import { Route as ToolsRetirementSavingsCalculatorRouteImport } from './routes/tools.retirement-savings-calculator'
import { Route as ToolsEmergencyFundCalculatorRouteImport } from './routes/tools.emergency-fund-calculator'
import { Route as ToolsDebtPayoffCalculatorRouteImport } from './routes/tools.debt-payoff-calculator'
import { Route as ToolsCreditScoreEstimatorRouteImport } from './routes/tools.credit-score-estimator'
import { Route as ToolsCreditCardPayoffCalculatorRouteImport } from './routes/tools.credit-card-payoff-calculator'
import { Route as ToolsCompoundInterestCalculatorRouteImport } from './routes/tools.compound-interest-calculator'
import { Route as ToolsBudgetPlannerRouteImport } from './routes/tools.budget-planner'
import { Route as AboutYinkaOlayokunRouteImport } from './routes/about.yinka-olayokun'
import { Route as PillarPostRouteImport } from './routes/$pillar.$post'
import { Route as ApiPublicNewsletterRouteImport } from './routes/api/public/newsletter'
import { Route as ApiPublicNewsletterCronRouteImport } from './routes/api/public/newsletter.cron'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingRoute = SavingRouteImport.update({
  id: '/saving',
  path: '/saving',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirementRoute = RetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingRoute = InvestingRouteImport.update({
  id: '/investing',
  path: '/investing',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtTaxesInsuranceRoute = DebtTaxesInsuranceRouteImport.update({
  id: '/debt-taxes-insurance',
  path: '/debt-taxes-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardsRoute = CreditCardsRouteImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetingRoute = BudgetingRouteImport.update({
  id: '/budgeting',
  path: '/budgeting',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSavingsGoalCalculatorRoute =
  ToolsSavingsGoalCalculatorRouteImport.update({
    id: '/tools/savings-goal-calculator',
    path: '/tools/savings-goal-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsRetirementSavingsCalculatorRoute =
  ToolsRetirementSavingsCalculatorRouteImport.update({
    id: '/tools/retirement-savings-calculator',
    path: '/tools/retirement-savings-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsEmergencyFundCalculatorRoute =
  ToolsEmergencyFundCalculatorRouteImport.update({
    id: '/tools/emergency-fund-calculator',
    path: '/tools/emergency-fund-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsDebtPayoffCalculatorRoute =
  ToolsDebtPayoffCalculatorRouteImport.update({
    id: '/tools/debt-payoff-calculator',
    path: '/tools/debt-payoff-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCreditScoreEstimatorRoute =
  ToolsCreditScoreEstimatorRouteImport.update({
    id: '/tools/credit-score-estimator',
    path: '/tools/credit-score-estimator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCreditCardPayoffCalculatorRoute =
  ToolsCreditCardPayoffCalculatorRouteImport.update({
    id: '/tools/credit-card-payoff-calculator',
    path: '/tools/credit-card-payoff-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCompoundInterestCalculatorRoute =
  ToolsCompoundInterestCalculatorRouteImport.update({
    id: '/tools/compound-interest-calculator',
    path: '/tools/compound-interest-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsBudgetPlannerRoute = ToolsBudgetPlannerRouteImport.update({
  id: '/tools/budget-planner',
  path: '/tools/budget-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutYinkaOlayokunRoute = AboutYinkaOlayokunRouteImport.update({
  id: '/about/yinka-olayokun',
  path: '/about/yinka-olayokun',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarPostRoute = PillarPostRouteImport.update({
  id: '/$pillar/$post',
  path: '/$pillar/$post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterRoute = ApiPublicNewsletterRouteImport.update({
  id: '/api/public/newsletter',
  path: '/api/public/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterCronRoute = ApiPublicNewsletterCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => ApiPublicNewsletterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banking': typeof BankingRoute
  '/budgeting': typeof BudgetingRoute
  '/contact': typeof ContactRoute
  '/credit-cards': typeof CreditCardsRoute
  '/debt-taxes-insurance': typeof DebtTaxesInsuranceRoute
  '/disclaimer': typeof DisclaimerRoute
  '/investing': typeof InvestingRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/retirement': typeof RetirementRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saving': typeof SavingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$pillar/$post': typeof PillarPostRoute
  '/about/yinka-olayokun': typeof AboutYinkaOlayokunRoute
  '/tools/budget-planner': typeof ToolsBudgetPlannerRoute
  '/tools/compound-interest-calculator': typeof ToolsCompoundInterestCalculatorRoute
  '/tools/credit-card-payoff-calculator': typeof ToolsCreditCardPayoffCalculatorRoute
  '/tools/credit-score-estimator': typeof ToolsCreditScoreEstimatorRoute
  '/tools/debt-payoff-calculator': typeof ToolsDebtPayoffCalculatorRoute
  '/tools/emergency-fund-calculator': typeof ToolsEmergencyFundCalculatorRoute
  '/tools/retirement-savings-calculator': typeof ToolsRetirementSavingsCalculatorRoute
  '/tools/savings-goal-calculator': typeof ToolsSavingsGoalCalculatorRoute
  '/about/': typeof AboutIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRouteWithChildren
  '/api/public/newsletter/cron': typeof ApiPublicNewsletterCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banking': typeof BankingRoute
  '/budgeting': typeof BudgetingRoute
  '/contact': typeof ContactRoute
  '/credit-cards': typeof CreditCardsRoute
  '/debt-taxes-insurance': typeof DebtTaxesInsuranceRoute
  '/disclaimer': typeof DisclaimerRoute
  '/investing': typeof InvestingRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/retirement': typeof RetirementRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saving': typeof SavingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$pillar/$post': typeof PillarPostRoute
  '/about/yinka-olayokun': typeof AboutYinkaOlayokunRoute
  '/tools/budget-planner': typeof ToolsBudgetPlannerRoute
  '/tools/compound-interest-calculator': typeof ToolsCompoundInterestCalculatorRoute
  '/tools/credit-card-payoff-calculator': typeof ToolsCreditCardPayoffCalculatorRoute
  '/tools/credit-score-estimator': typeof ToolsCreditScoreEstimatorRoute
  '/tools/debt-payoff-calculator': typeof ToolsDebtPayoffCalculatorRoute
  '/tools/emergency-fund-calculator': typeof ToolsEmergencyFundCalculatorRoute
  '/tools/retirement-savings-calculator': typeof ToolsRetirementSavingsCalculatorRoute
  '/tools/savings-goal-calculator': typeof ToolsSavingsGoalCalculatorRoute
  '/about': typeof AboutIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRouteWithChildren
  '/api/public/newsletter/cron': typeof ApiPublicNewsletterCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banking': typeof BankingRoute
  '/budgeting': typeof BudgetingRoute
  '/contact': typeof ContactRoute
  '/credit-cards': typeof CreditCardsRoute
  '/debt-taxes-insurance': typeof DebtTaxesInsuranceRoute
  '/disclaimer': typeof DisclaimerRoute
  '/investing': typeof InvestingRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/retirement': typeof RetirementRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saving': typeof SavingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$pillar/$post': typeof PillarPostRoute
  '/about/yinka-olayokun': typeof AboutYinkaOlayokunRoute
  '/tools/budget-planner': typeof ToolsBudgetPlannerRoute
  '/tools/compound-interest-calculator': typeof ToolsCompoundInterestCalculatorRoute
  '/tools/credit-card-payoff-calculator': typeof ToolsCreditCardPayoffCalculatorRoute
  '/tools/credit-score-estimator': typeof ToolsCreditScoreEstimatorRoute
  '/tools/debt-payoff-calculator': typeof ToolsDebtPayoffCalculatorRoute
  '/tools/emergency-fund-calculator': typeof ToolsEmergencyFundCalculatorRoute
  '/tools/retirement-savings-calculator': typeof ToolsRetirementSavingsCalculatorRoute
  '/tools/savings-goal-calculator': typeof ToolsSavingsGoalCalculatorRoute
  '/about/': typeof AboutIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRouteWithChildren
  '/api/public/newsletter/cron': typeof ApiPublicNewsletterCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banking'
    | '/budgeting'
    | '/contact'
    | '/credit-cards'
    | '/debt-taxes-insurance'
    | '/disclaimer'
    | '/investing'
    | '/newsletter'
    | '/privacy'
    | '/retirement'
    | '/robots.txt'
    | '/saving'
    | '/sitemap.xml'
    | '/terms'
    | '/$pillar/$post'
    | '/about/yinka-olayokun'
    | '/tools/budget-planner'
    | '/tools/compound-interest-calculator'
    | '/tools/credit-card-payoff-calculator'
    | '/tools/credit-score-estimator'
    | '/tools/debt-payoff-calculator'
    | '/tools/emergency-fund-calculator'
    | '/tools/retirement-savings-calculator'
    | '/tools/savings-goal-calculator'
    | '/about/'
    | '/tools/'
    | '/api/public/newsletter'
    | '/api/public/newsletter/cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banking'
    | '/budgeting'
    | '/contact'
    | '/credit-cards'
    | '/debt-taxes-insurance'
    | '/disclaimer'
    | '/investing'
    | '/newsletter'
    | '/privacy'
    | '/retirement'
    | '/robots.txt'
    | '/saving'
    | '/sitemap.xml'
    | '/terms'
    | '/$pillar/$post'
    | '/about/yinka-olayokun'
    | '/tools/budget-planner'
    | '/tools/compound-interest-calculator'
    | '/tools/credit-card-payoff-calculator'
    | '/tools/credit-score-estimator'
    | '/tools/debt-payoff-calculator'
    | '/tools/emergency-fund-calculator'
    | '/tools/retirement-savings-calculator'
    | '/tools/savings-goal-calculator'
    | '/about'
    | '/tools'
    | '/api/public/newsletter'
    | '/api/public/newsletter/cron'
  id:
    | '__root__'
    | '/'
    | '/banking'
    | '/budgeting'
    | '/contact'
    | '/credit-cards'
    | '/debt-taxes-insurance'
    | '/disclaimer'
    | '/investing'
    | '/newsletter'
    | '/privacy'
    | '/retirement'
    | '/robots.txt'
    | '/saving'
    | '/sitemap.xml'
    | '/terms'
    | '/$pillar/$post'
    | '/about/yinka-olayokun'
    | '/tools/budget-planner'
    | '/tools/compound-interest-calculator'
    | '/tools/credit-card-payoff-calculator'
    | '/tools/credit-score-estimator'
    | '/tools/debt-payoff-calculator'
    | '/tools/emergency-fund-calculator'
    | '/tools/retirement-savings-calculator'
    | '/tools/savings-goal-calculator'
    | '/about/'
    | '/tools/'
    | '/api/public/newsletter'
    | '/api/public/newsletter/cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankingRoute: typeof BankingRoute
  BudgetingRoute: typeof BudgetingRoute
  ContactRoute: typeof ContactRoute
  CreditCardsRoute: typeof CreditCardsRoute
  DebtTaxesInsuranceRoute: typeof DebtTaxesInsuranceRoute
  DisclaimerRoute: typeof DisclaimerRoute
  InvestingRoute: typeof InvestingRoute
  NewsletterRoute: typeof NewsletterRoute
  PrivacyRoute: typeof PrivacyRoute
  RetirementRoute: typeof RetirementRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SavingRoute: typeof SavingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  PillarPostRoute: typeof PillarPostRoute
  AboutYinkaOlayokunRoute: typeof AboutYinkaOlayokunRoute
  ToolsBudgetPlannerRoute: typeof ToolsBudgetPlannerRoute
  ToolsCompoundInterestCalculatorRoute: typeof ToolsCompoundInterestCalculatorRoute
  ToolsCreditCardPayoffCalculatorRoute: typeof ToolsCreditCardPayoffCalculatorRoute
  ToolsCreditScoreEstimatorRoute: typeof ToolsCreditScoreEstimatorRoute
  ToolsDebtPayoffCalculatorRoute: typeof ToolsDebtPayoffCalculatorRoute
  ToolsEmergencyFundCalculatorRoute: typeof ToolsEmergencyFundCalculatorRoute
  ToolsRetirementSavingsCalculatorRoute: typeof ToolsRetirementSavingsCalculatorRoute
  ToolsSavingsGoalCalculatorRoute: typeof ToolsSavingsGoalCalculatorRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiPublicNewsletterRoute: typeof ApiPublicNewsletterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saving': {
      id: '/saving'
      path: '/saving'
      fullPath: '/saving'
      preLoaderRoute: typeof SavingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirement': {
      id: '/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof RetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing': {
      id: '/investing'
      path: '/investing'
      fullPath: '/investing'
      preLoaderRoute: typeof InvestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debt-taxes-insurance': {
      id: '/debt-taxes-insurance'
      path: '/debt-taxes-insurance'
      fullPath: '/debt-taxes-insurance'
      preLoaderRoute: typeof DebtTaxesInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-cards': {
      id: '/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof CreditCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgeting': {
      id: '/budgeting'
      path: '/budgeting'
      fullPath: '/budgeting'
      preLoaderRoute: typeof BudgetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/savings-goal-calculator': {
      id: '/tools/savings-goal-calculator'
      path: '/tools/savings-goal-calculator'
      fullPath: '/tools/savings-goal-calculator'
      preLoaderRoute: typeof ToolsSavingsGoalCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/retirement-savings-calculator': {
      id: '/tools/retirement-savings-calculator'
      path: '/tools/retirement-savings-calculator'
      fullPath: '/tools/retirement-savings-calculator'
      preLoaderRoute: typeof ToolsRetirementSavingsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/emergency-fund-calculator': {
      id: '/tools/emergency-fund-calculator'
      path: '/tools/emergency-fund-calculator'
      fullPath: '/tools/emergency-fund-calculator'
      preLoaderRoute: typeof ToolsEmergencyFundCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/debt-payoff-calculator': {
      id: '/tools/debt-payoff-calculator'
      path: '/tools/debt-payoff-calculator'
      fullPath: '/tools/debt-payoff-calculator'
      preLoaderRoute: typeof ToolsDebtPayoffCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/credit-score-estimator': {
      id: '/tools/credit-score-estimator'
      path: '/tools/credit-score-estimator'
      fullPath: '/tools/credit-score-estimator'
      preLoaderRoute: typeof ToolsCreditScoreEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/credit-card-payoff-calculator': {
      id: '/tools/credit-card-payoff-calculator'
      path: '/tools/credit-card-payoff-calculator'
      fullPath: '/tools/credit-card-payoff-calculator'
      preLoaderRoute: typeof ToolsCreditCardPayoffCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compound-interest-calculator': {
      id: '/tools/compound-interest-calculator'
      path: '/tools/compound-interest-calculator'
      fullPath: '/tools/compound-interest-calculator'
      preLoaderRoute: typeof ToolsCompoundInterestCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/budget-planner': {
      id: '/tools/budget-planner'
      path: '/tools/budget-planner'
      fullPath: '/tools/budget-planner'
      preLoaderRoute: typeof ToolsBudgetPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/yinka-olayokun': {
      id: '/about/yinka-olayokun'
      path: '/about/yinka-olayokun'
      fullPath: '/about/yinka-olayokun'
      preLoaderRoute: typeof AboutYinkaOlayokunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pillar/$post': {
      id: '/$pillar/$post'
      path: '/$pillar/$post'
      fullPath: '/$pillar/$post'
      preLoaderRoute: typeof PillarPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter': {
      id: '/api/public/newsletter'
      path: '/api/public/newsletter'
      fullPath: '/api/public/newsletter'
      preLoaderRoute: typeof ApiPublicNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter/cron': {
      id: '/api/public/newsletter/cron'
      path: '/cron'
      fullPath: '/api/public/newsletter/cron'
      preLoaderRoute: typeof ApiPublicNewsletterCronRouteImport
      parentRoute: typeof ApiPublicNewsletterRoute
    }
  }
}

interface ApiPublicNewsletterRouteChildren {
  ApiPublicNewsletterCronRoute: typeof ApiPublicNewsletterCronRoute
}

const ApiPublicNewsletterRouteChildren: ApiPublicNewsletterRouteChildren = {
  ApiPublicNewsletterCronRoute: ApiPublicNewsletterCronRoute,
}

const ApiPublicNewsletterRouteWithChildren =
  ApiPublicNewsletterRoute._addFileChildren(ApiPublicNewsletterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankingRoute: BankingRoute,
  BudgetingRoute: BudgetingRoute,
  ContactRoute: ContactRoute,
  CreditCardsRoute: CreditCardsRoute,
  DebtTaxesInsuranceRoute: DebtTaxesInsuranceRoute,
  DisclaimerRoute: DisclaimerRoute,
  InvestingRoute: InvestingRoute,
  NewsletterRoute: NewsletterRoute,
  PrivacyRoute: PrivacyRoute,
  RetirementRoute: RetirementRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SavingRoute: SavingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  PillarPostRoute: PillarPostRoute,
  AboutYinkaOlayokunRoute: AboutYinkaOlayokunRoute,
  ToolsBudgetPlannerRoute: ToolsBudgetPlannerRoute,
  ToolsCompoundInterestCalculatorRoute: ToolsCompoundInterestCalculatorRoute,
  ToolsCreditCardPayoffCalculatorRoute: ToolsCreditCardPayoffCalculatorRoute,
  ToolsCreditScoreEstimatorRoute: ToolsCreditScoreEstimatorRoute,
  ToolsDebtPayoffCalculatorRoute: ToolsDebtPayoffCalculatorRoute,
  ToolsEmergencyFundCalculatorRoute: ToolsEmergencyFundCalculatorRoute,
  ToolsRetirementSavingsCalculatorRoute: ToolsRetirementSavingsCalculatorRoute,
  ToolsSavingsGoalCalculatorRoute: ToolsSavingsGoalCalculatorRoute,
  AboutIndexRoute: AboutIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiPublicNewsletterRoute: ApiPublicNewsletterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
