// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lihcydyxacmslzjnblse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpaGN5ZHl4YWNtc2x6am5ibHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0NDE4MTgsImV4cCI6MjA5NDAxNzgxOH0.duCtgjIYxYRsopQwtW2Q60Db2yrTDcDMiyT-33XZv6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});